baseURL = "https://examplesite.com/"
title = "Marians Blog"
paginate = 5
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
pygmentsUseClasses = true

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Marians Blog"
description = "Description"
keywords = [ "Blog" ]
author = "Marian Hahne"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "02.01.2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

  [params.assets]
  favicon = "<link / abs url>"
  favicon16x16 = "<link / abs url>"
  favicon32x32 = "<link / abs url>"
  apple_touch_icon = "<link / abs url>"
  safari_pinned_tab = "<link / abs url>"

  [params.label]
  text = "Home"
  icon = "/apple-touch-icon.png"
  iconHeight = 35

  [params.homeInfoParams]
  Title = "Hallo Besucher ðŸ‘‹"
  Content = "Willkommen auf meinem Blog"

  [[params.socialIcons]]
  name = "codeberg"
  url = "https://codeberg.org/rotespferd"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/rotespferd"

  [[params.socialIcons]]
  name = "mastodon"
  url = "https://nrw.social/@rotespferd"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/marian-hahne-a531b8106/"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

[[menu.main]]
identifier = "archiv"
name = "Archiv"
url = "/archiv/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "Themen"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "example"
name = "example.org"
url = "https://example.org"
weight = 30

[markup.highlight]
noClasses = false
